	--CREATE SEQUENCE seq_person;
	--CREATE SEQUENCE seq_app_user;

  create table PERSON(ID INTEGER NOT NULL,FIRST_NAME VARCHAR(100),LAST_NAME VARCHAR(100),NUMBER INTEGER,BRITH_DATE DATE);

  create table users(
	  username varchar_ignorecase(50) not null primary key,
	  password varchar_ignorecase(50) not null,
	  enabled boolean not null);

  create table authorities (
	  username varchar_ignorecase(50) not null,
	  authority varchar_ignorecase(50) not null,
	  constraint fk_authorities_users foreign key(username) references users(username));
	  create unique index ix_auth_username on authorities (username,authority);

	create table groups (
	  id bigint generated by default as identity(start with 0) primary key,
	  group_name varchar_ignorecase(50) not null);

	create table group_authorities (
	  group_id bigint not null,
	  authority varchar(50) not null,
	  constraint fk_group_authorities_group foreign key(group_id) references groups(id));

	create table group_members (
	  id bigint generated by default as identity(start with 0) primary key,
	  username varchar(50) not null,
	  group_id bigint not null,
	  constraint fk_group_members_group foreign key(group_id) references groups(id));
	  -- Persistent Login (Remember-Me) Schema
	  create table persistent_logins (
	  username varchar(64) not null,
	  series varchar(64) primary key,
	  token varchar(64) not null,
	  last_used timestamp not null);


	create table oauth_client_details (
	  client_id VARCHAR(256) PRIMARY KEY,
	  resource_ids VARCHAR(256),
	  client_secret VARCHAR(256),
	  scope VARCHAR(256),
	  authorized_grant_types VARCHAR(256),
	  web_server_redirect_uri VARCHAR(256),
	  authorities VARCHAR(256),
	  access_token_validity INTEGER,
	  refresh_token_validity INTEGER,
	  additional_information VARCHAR(4096)
	);

	create table oauth_client_token (
	  token_id VARCHAR(256),
	  token LONGVARBINARY,
	  authentication_id VARCHAR(256),
	  user_name VARCHAR(256),
	  client_id VARCHAR(256)
	);

	create table oauth_access_token (
	  token_id VARCHAR(256),
	  token LONGVARBINARY,
	  authentication_id VARCHAR(256),
	  user_name VARCHAR(256),
	  client_id VARCHAR(256),
	  authentication LONGVARBINARY,
	  refresh_token VARCHAR(256)
	);

	create table oauth_refresh_token (
	  token_id VARCHAR(256),
	  token LONGVARBINARY,
	  authentication LONGVARBINARY
	);

	create table oauth_code (
	  code VARCHAR(256), authentication LONGVARBINARY
	);

	-- customized oauth_client_details table
	create table ClientDetails (
	  appId VARCHAR(256) PRIMARY KEY,
	  resourceIds VARCHAR(256),
	  appSecret VARCHAR(256),
	  scope VARCHAR(256),
	  grantTypes VARCHAR(256),
	  redirectUrl VARCHAR(256),
	  authorities VARCHAR(256),
	  access_token_validity INTEGER,
	  refresh_token_validity INTEGER,
	  additionalInformation VARCHAR(4096)
	);
	ALTER TABLE PERSON ADD PRIMARY KEY (ID);
